# Generated by Django 5.2.4 on 2025-07-04 01:28

import eweb.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nucleotide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', eweb.core.fields.SequenceField(blank=True, default='', verbose_name='Sequence')),
            ],
        ),
    ]
