# Generated by Django 5.2.4 on 2025-07-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleotide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleotide',
            name='seq',
            field=models.TextField(blank=True, default='', verbose_name='Sequence'),
        ),
    ]
