# Generated by Django 5.2.4 on 2025-07-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleotide', '0003_nucleotide_description_nucleotide_entrez_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleotide',
            name='seq_length',
            field=models.IntegerField(default=0, verbose_name='Sequence Length'),
        ),
    ]
