# Generated by Django 5.2.4 on 2025-07-09 17:50

import eweb.nucleotide.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleotide', '0004_nucleotide_seq_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nucleotide',
            options={'ordering': ('entrez_id',), 'verbose_name': 'Nucleotide'},
        ),
        migrations.RemoveField(
            model_name='nucleotide',
            name='seq',
        ),
        migrations.AddField(
            model_name='nucleotide',
            name='fasta_file',
            field=models.FileField(blank=True, null=True, upload_to=eweb.nucleotide.models.nucleotide_filepath, verbose_name='Nuncleotide Seq as fasta file'),
        ),
        migrations.AlterField(
            model_name='nucleotide',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nucleotide',
            name='entrez_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Entrez ID'),
        ),
        migrations.AlterField(
            model_name='nucleotide',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
