# Generated by Django 5.2.4 on 2025-07-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleotide', '0005_alter_nucleotide_options_remove_nucleotide_seq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nucleotide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nucleotide',
            name='name',
        ),
        migrations.AddField(
            model_name='nucleotide',
            name='extra',
            field=models.CharField(default='', max_length=250, verbose_name='Extra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nucleotide',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
