# Generated by Django 5.2.4 on 2025-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleotide', '0006_remove_nucleotide_description_remove_nucleotide_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleotide',
            name='extra',
            field=models.CharField(max_length=500, verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='nucleotide',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
    ]
